### ISSUE TITLE
Setting build number (CFBundleVersion) as integer, xcode expecting a string

### ISSUE THREAD

**Issue by robations** [HausennTechnologies/capacitor-set-version#159]
Setting the version like this:

```
npx capacitor-set-version -v 1.2.3 -b 1234 ./
```

sets the CFBundleVersion to an `<integer>1234</integer>`, but XCode complains until you change this back to a `<string>1234</string>`.

Is this expected or a bug?

I'd guess something is parsing the build number as a JS number and the plist library is applying the property value based on type.

**Comment by chrisspiegl** [comment]
I found this as well and consider it a bug. This broke my app build and crashed the app upon launch.

The worst part was that Xcode didn't quite catch it and thus it took me hours to figure out that it even was related to this issue.

I hope we can get this fixed because I consider the idea of syncing the version number with this plugin to be a great idea.

**Comment by chrisspiegl** [comment]
I just tried to figure out the code and I think I could propose a pull request, but wonder if it @HausennTechnologies would consider it since this issue has not gotten any attention?

Mostly it seems the input values have to be adjusted or the `setIOSBuild` function needs to parse the value into a string before writing it.

https://github.com/HausennTechnologies/capacitor-set-version/blob/61731988d7413893963c94e79121429d405ae14c/src/utils.ts#L82

**Comment by daviesdoclc** [comment]
Would love to see this fixed as well.

**Comment by DKrepsky** [comment]
Hello guys.
Sorry for the late response on this one. 

@chrisspiegl that is right, just casting it to string is enough.

Also, any PR are welcome.

For this one, I'll fix it today.

Thanks

**Comment by DKrepsky** [comment]
This should be fixed now.
If the bug persists, please open a new issue.

**Comment by chrisspiegl** [comment]
Tested, seems to be working.
